### ISSUE TITLE
What is this trying to open with subprocess?

### ISSUE THREAD

**Issue by joshuajonah** [vorushin/sublimetext_python_checker#1]
``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 112, in on_load
  File "./python_checker.py", line 17, in on_load
  File "./python_checker.py", line 38, in check_and_mark
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 1139, in _execute_child
OSError: [Errno 2] No such file or directory
```

**Comment by joshuajonah** [comment]
I'm an idiot
